development:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: chat_development

test: 
  adapter: async

production: 
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: chat_production
  # channel_prefix may be provided to avoid channel name collisions when using the same redis server for multiple applications.